### ISSUE TITLE
What is the meaning of WinSz being 20 for Gallo and Soros?

### ISSUE THREAD

**Issue by seyfu-t** [iyyun/Barcode_1D#3]

**Comment by iyyun** [comment]
The "WinSZ' refer to the size of the block filter (or Box filter) required for barcode localization. Maybe... In the paper, it is set to 30 or 31.

**Comment by seyfu-t** [comment]
hmm ok thank you, I've skimmed over the paper a bit to understand a bit more, but I think it's better that I keep your values.

I don't know if github notified you, but I tagged you in a [project of mine](https://github.com/seyfu-t/JBarcode_1D), which is basically just a re-implementation of your C++ code in Java. The goal is to make it usable as maven library or as a cli tool

**Comment by iyyun** [comment]
I hope it turns out well.

**Comment by seyfu-t** [comment]
Thank you, I hope too
